next.config.js, utils/prices.js
**What**
- Fixes getVariantPrices function
**How**
Changed
```js
export function getVariantPrice(cart, variant) {
let taxRate = getTaxRate(cart);
let moneyAmount = variant.prices.find(
(p) =>
p.currency_code.toLowerCase() === cart.currency_code.toLowerCase()
);
if (moneyAmount && moneyAmount.amount) {
return (moneyAmount.amount * (1 + taxRate));
}
return undefined;
}
```
to
```js
export function getVariantPrice(cart, variant) {
let taxRate = getTaxRate(cart);
let moneyAmount = variant.prices.find(
(p) =>
p.currency_code.toLowerCase() === cart.region.currency_code.toLowerCase()
);
if (moneyAmount && moneyAmount.amount) {
return (moneyAmount.amount * (1 + taxRate)) / 100;
}
return undefined;
}
```
=> fix: getVariantPrices now returns the correct prices

src/lib/context/store-context.tsx
When a cart is created, it may return `cart.shipping_address.country_code` if the backend is able to detect the user's country. This change updates the starter to make use of the `cart.shipping_address.country_code`, if there is one, to auto select the country.
Closes: #73
This is helpful as it reduces friction for end users by reducing the steps they need to take in order to purchase something.
`ensureRegion()` was updated to take in a country code if one was present.
This was manually tested by making use of an IP lookup plugin like the [Maxmind IP Lookup plugin](https://www.npmjs.com/package/medusa-plugin-ip-lookup-maxmind), to automatically set the region and country. The following screenshot shows the cart with the shipping address as US and the country selected as US.
=> Update starter to auto select country if cart has shipping country set

src/modules/common/components/modal/index.tsx
Fixes #77 by using `flex-1` class instead of `h-full`
After changes:
=> Fix modal cutting content issue

src/modules/layout/components/cart-dropdown/index.tsx
The cart button was not clickable in the demo. For some reason the Popover.Button component doesn't work well with the Next Link. I've moved the link component into the button and it seems to fix the issue.
=> fix: move link into popover button

src/modules/search/components/desktop-hit/index.tsx, src/modules/search/components/mobile-hit/index.tsx
When enabling search, the error `NextRouter` was not mounted occurs.
More info: https://nextjs.org/docs/messages/next-router-not-mounted
=> fix NextRouter was not mounted error in Search

tailwind.config.js
The tailwind classes in `src/app` probably don't work unless they exist in other directories.
=> Update tailwind.config.js to include src/app

src/modules/layout/components/dropdown-menu/index.tsx
Removes outline around Store button in the main nav component. The outline pops up when you click the store button.
=> fix: remove store button outline in main nav

src/modules/layout/components/cart-dropdown/index.tsx
See: https://github.com/medusajs/nextjs-starter-medusa/blob/9f0274ab56feb971c89ff71d3dfbe2da6e5939e0/src/modules/layout/components/cart-dropdown/index.tsx#L107
=> fix: Subtotal in cart is excl. taxes

.env.template
Based on [search-client.ts](https://github.com/medusajs/nextjs-starter-medusa/blob/main/src/lib/search-client.ts), the environment variable name for the search index should be `NEXT_PUBLIC_INDEX_NAME` instead of `NEXT_PUBLIC_SEARCH_INDEX_NAME`
=> fix: fix incorrect variable name in .env.template

src/modules/checkout/components/payment-wrapper/index.tsx
Prevents `loadStripe()` from being called with an empty Stripe key. This was causing errors in Firefox.
=> fix: fallback when stripe key is empty

src/modules/account/components/order-card/index.tsx
Fixes a bug where where every product would show the first products thumbnail in the account order overview.
=> fix: show proper thumbnails on order overview

src/app/(main)/search/[query]/page.tsx, src/app/(main)/search/actions.ts, src/lib/search-client.ts, src/modules/search/templates/search-results-template/index.tsx
In this PR:
- Adds MeiliSearch support to the search results page.
- Resets MeiliSearch as the default search provider.
- Adds in a '0 results' state for the search page.
=> fix: meilisearch support

src/modules/common/components/modal/index.tsx
=> fix: center the search page position

src/app/layout.tsx, src/lib/context/checkout-context.tsx
fixes this
```
Unhandled Runtime Error
Error: Could not find Elements context; You need to wrap the part of your app that calls useStripe() in an <Elements> provider.
Source
src/modules/checkout/components/payment-button/index.tsx (76:26) @ useStripe
74 | const { onPaymentCompleted } = useCheckout()
75 |
> 76 | const stripe = useStripe()
|                        ^
77 | const elements = useElements()
78 | const card = elements?.getElement("cardNumber")
79 |
```
=> checkout stripe error

.env.template, src/middleware.ts, src/modules/products/templates/index.tsx, src/modules/products/templates/product-actions-wrapper/index.tsx
In this PR:
- Default region is now an environment variable.
- When the user visits an url without region param, and the default region is not available on the Medusa server, it will default to the first available region. This prevents an endless redirect loop in case the default region is not set properly.
- On statically rendered product pages, prices are refetched on request time to check for user-specific pricing.
=> fix: region and dynamic prices

src/modules/search/templates/search-results-template/index.tsx
the query string displayed for "Search Results for" should be decoded
=> Search Result page query fix

src/app/not-found.tsx
This PR aims to fix the not-found link to frontpage.
not-found.tsx file is using the InteractiveLink component to redirect to the frontpage, but the not-found page does not have access to the countryCode param, so right now is redirecting to "/undefined". To fix this issue, InteractiveLink can be replaced to the Link component from next/link.
=> fix not-found link to frontpage

src/modules/checkout/components/payment-wrapper/index.tsx, src/modules/checkout/components/payment/index.tsx
**In this PR:**
Fixes https://github.com/medusajs/nextjs-starter-medusa/issues/247 where Stripe elements tried to render before the Elements context was properly loaded.
**Solution:**
Adds in a `StripeContext` provider that returns `true` when the Elements context is ready. You can hook into this context to conditionally render Stripe elements in your checkout form.
=> fix: checkout breaking when Stripe is the only payment provider

package.json, src/lib/config.ts, yarn.lock
In this PR:
- Removes the Axios fetch adapter (for now). It was added to let our JS client play nicely with Next.js caching, but was breaking the Starter when installing with `npm`. All get functions are wrapped in React `cache()`, so everything will still be cached properly.
=> fix: rm axios fetch adapter

tailwind.config.js
System dark mode was causing issues with newer Tailwind versions. This PR ensures light mode regardless of the user system setting.
=> fix: enforce light mode

src/modules/account/actions.ts, src/modules/account/components/account-nav/index.tsx
Fixes a bug where the redirect on sign out would break if there was no `nextUrl` header present.
=> fix: signOut redirect bug

src/lib/data/index.ts, src/modules/checkout/templates/checkout-form/index.tsx
Fixes an issue where shipping options with `price_type: calculated` would have no `amount`. The `listShippingOptions` fetch was using the wrong method.
=> fix: use listCartOptions instead of list

src/modules/checkout/components/payment-button/index.tsx
- Change payment provider ID switch cases to check if a provider ID starts with a value. That's because the last part of the provider ID is configurable by the developer in the Medusa config, so it may be different than what we expect.
- Fix stripe's provider ID to start with `pp_stripe_`
=> fix: payment provider ID detection

next-env.d.ts, package.json, src/lib/data/customer.ts, src/modules/products/components/related-products/index.tsx, yarn.lock
This pull request includes several updates to dependencies, type assertions, and code cleanup. The most important changes include updating MedusaJS dependencies to release candidates, adding type assertions in authentication functions, and optimizing import statements.
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L25-R26): Updated `@medusajs/js-sdk`, `@medusajs/ui`, `@medusajs/types`, and `@medusajs/ui-preset` from "preview" to "rc". [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L25-R26) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L50-R50)
Type assertions:
* [`src/lib/data/customer.ts`](diffhunk://#diff-b3995837bd106a2e0078382d2df244 …
=> fix: ts errors

src/app/[countryCode]/(main)/products/[handle]/page.tsx
#391 
This pull request includes changes to fix the error caused by `generateStaticParams` in `src/app/[countryCode]/(main)/products/[handle]/page.tsx`.
Problem:
- Production build fails with DYNAMIC_SERVER_USAGE error
- Multiple unnecessary API calls during static generation
Fix:
- Single optimized SDK call for product handles
- Improved error handling
- Maintains Next.js caching patterns
=> Fix: Optimize product page static generation

README.md
The link to stripe integration goes to 404 so I updated it. But I didn't find a link to paypal integration in the new docs.
=> chore: fix link to payment docs in README.md

src/lib/data/customer.ts
The functions `signout` and `transferCart` use hard-coded tags for revalidation that do not include the cache id. Because of this the transfer cart banner is not hidden on success and signing out leads to a 404, requiring a manual refresh. This PR addresses that.
The hardcoded "auth" tag also has no associated queries, so it has been removed.
=> Fix cache revalidation in customer actions

src/lib/data/customer.ts
- Use dynamic customer cache tag to unvalidate customer in signout function
- Prevent Customer API call if no JWT is set (and avoid 401)
- Remove unnecessary `customer` cache tag
- Remove unnecessary `auth` cache tag
=> fix: customer server action & cache

src/lib/data/cart.ts
Currently, most server actions that update the cart do not revalidate the tags for shipping options, leading to stale data in the checkout page. In particular:
- changing the checkout country when multiple service zones with different countries are present
- changing the total price of the cart when price rules/calculated price is present. Namely updating, deleting, adding cart line items or applying promotion codes
This PR revalidates the tag in the respective server actions
=> Revalidate shipping options cache tags whenever cart is updated

src/lib/data/products.ts
This pull request addresses the issue with the offset calculation in the product listing. The offset was previously incorrect, causing pagination to display wrong product data. 
Changes include:
- Fixing the calculation of the offset for product pagination.
- Ensuring that products are displayed correctly when navigating through pages.
This should resolve issues related to displaying products in the correct order and pagination working as expected.
Fixes #441
=> Fix offset calculation in product listing (Fixes #441)

src/lib/util/product.ts, src/modules/products/components/product-actions/mobile-actions.tsx
mobile-actions.tsx: On mobile, for a product with only one variant (and one set of options), there shouldn't be any option select:
**Before**
**After**
=> fix: Mobile product options select showing when there's no options

src/modules/order/components/shipping-details/index.tsx
When my shipping method is $30 for instance, It was $30,00 and this PR fixes it to $30.00
=> fix: replace decimal separator in order confirmation

src/modules/account/components/profile-billing-address/index.tsx
Phone number is required from the BE side:
"Error: Invalid request: Expected type: 'string' for field 'phone', got: 'null'"}
=> Fix: add missing phone for billing address

src/lib/data/cart.ts
**What**
Do not fetch non necessary data
=> refactor: lighten cart data method retrieval

src/middleware.ts
CLOSES #502 
Show error message if no region with country code could be found so the storefront does not enter infinite loop
=> fix: handle when no region with country configured
