medusajs/nextjs-starter-medusa

README.md
package.json

**What**
- Changed dev port from default 3000 -> 8000
- Removed note on changing STORE_CORS from README
**Why**
- Removes the need for changing STORE_CORS, when trying out different starters.

fix: changed dev port to 8000, so it is inline with other starters

---

README.md

PR #8 fixed the script, but line 64 still showed `http://localhost:3000`.

fix: wrong url in quickstart

---

components/layout/nav-bar.jsx
context/store-context.js
package.json
pages/index.js
pages/product/[id].js
yarn.lock

Reverts medusajs/nextjs-starter-medusa#13

Revert "feat: Update use of `@medusa/medusa-js`"

---

package.json

Added keywords and description to the package to ensure it is scraped into the new website.

chore: added keywords and description

---

README.md
netlify.toml

Added necessary file to allow deploying to Netlify with a button and added the button to README

docs: added support to deploy to Netlify

---

src/lib/context/store-context.tsx

**What**
Correctly used saved region to create new cart after completing an order.
closes #44

fix: Use saved region on subsequent carts

---

next.config.js
package.json
src/lib/context/checkout-context.tsx
src/lib/util/get-product-handles.ts
src/modules/checkout/components/shipping/index.tsx
src/modules/common/components/head/index.tsx
src/modules/layout/components/country-select/index.tsx
src/types/global.ts
yarn.lock

**What**
- Upgrades packages @medusajs/medusa, @medusajs/medusa-js, and medusa-react to the latest versions.
- Fixes resulting build errors due to updated types.
**Why**
- The previous dependency of SQLite was causing issues on some newer Macs.

feat: upgrade version and fix build errors

---

src/modules/products/components/mobile-actions/index.tsx

Fixed: the button label on the mobile action template to change on the basis of stock availability

---

package.json
src/lib/context/account-context.tsx
src/lib/context/store-context.tsx
src/modules/account/components/account-nav/index.tsx
yarn.lock

**What**
- Updates versions of Medusa and JS client.
- Adds the ability for users to log out.

feat: Add deleteSession to account layour

---

src/pages/_app.tsx
src/types/global.ts

**What**
- Adds dehydratedState to pageProps type in _app

fix: add dehydratedState to pageProps type

---

src/modules/products/components/product-tabs/index.tsx

Fixed incorrect product property in the `ProductInfoTab`

fix: change origin_country to material in product info

---

src/modules/account/components/login/index.tsx
src/modules/account/components/register/index.tsx

Loading state for auth

---

src/modules/common/components/modal/index.tsx

Fix: Modal scrollable

---

package-lock.json
package.json
yarn.lock

**What**
- upgrade `medusa-js` and `medusa-react` versions to fix NPM conflicts

chore: upgrade medusa version

---

src/lib/context/store-context.tsx
src/modules/order/components/onboarding-cta/index.tsx
src/modules/order/templates/order-completed-template.tsx

Adds support for creating a test order as part of the admin onboarding flow.

feat: onboarding flow

---

src/modules/order/components/onboarding-cta/index.tsx

Updates the onboarding order url to the proper format.

fix: onboarding order url

---

README.md

changed direction to update store-config.json to store.config.json when changing feature flag for search integration.

Edit incorrect file reference in README.md

---

src/app/api/categories/[category]/[subcategory]/route.ts
src/app/api/categories/route.ts
src/app/api/collections/[handle]/route.ts
src/app/api/collections/route.ts
src/app/api/products/[handle]/route.ts
src/app/api/products/route.ts
src/modules/products/components/product-onboarding-cta/index.tsx
src/modules/products/templates/index.tsx

In this PR:
- Added onboarding CTA component to product pages, as part of the admin onboarding setup.

feat: add onboarding CTA to product page

---

src/lib/medusa-fetch/index.ts

Reduced the default REVALIDATE_WINDOW from 1000 hours to 30 minutes.
Closes #181

Set default REVALIDATE_WINDOW to 30 min.

---

README.md
next.config.js
package.json
yarn.lock

- Upgrades Next.js version to ^14.0.0
- Minor changes to `next.config.js`

chore: upgrade to Next.js 14

---

src/modules/account/templates/login-template.tsx

fix: adjust login-template padding

---

src/lib/data/index.ts

Removes the import from `@medusajs/utils/dist/feature-flags` which was causing some issues (and no longer needed).

fix: medusav2 feature flag

---

src/lib/context/checkout-context.tsx
src/modules/checkout/components/payment-button/index.tsx
src/modules/checkout/components/payment-container/index.tsx
src/modules/checkout/components/payment-stripe/index.tsx
src/modules/checkout/components/payment-wrapper/index.tsx
src/modules/checkout/components/payment/index.tsx
src/modules/checkout/components/review/index.tsx
src/modules/checkout/components/shipping/index.tsx
src/modules/common/components/cart-totals/index.tsx

In this PR:
- Fixes issues with the Stripe Elements wrapper
- Adds form validation for Stripe card payments
- Some other improvements/fixes

fix: stripe checkout issues

---

src/modules/layout/components/country-select/index.tsx

Fix this issue [issue:5567](https://github.com/medusajs/medusa/issues/5567)

pass `as` to ListBox

---

.env.template

Updated link to reflect changes to heading in the docs accordingly.

update docs link in .env.template

---

src/modules/layout/components/cart-dropdown/index.tsx

The link for the store is fixed.  "store" -> "/store"

[FIX] incorrect href

---

package.json
src/middleware.ts
yarn.lock

The new middleware was messing up the admin onboarding flow - should be fixed now.

fix: onboarding bug

---

src/modules/checkout/components/addresses/index.tsx
src/modules/checkout/components/shipping-address/index.tsx

In this PR:
- Checkout: change "Address" header to "Shipping Address"
- Update same as billing checkbox label for clarity

fix: shipping address labels

---

src/modules/account/actions.ts

fix: redirect only when nextUrl exists. resolve #282

---

.github/workflows/test-e2e.yaml
playwright.config.ts

~~Note I'm testing out some of the functionality, will let you know when the PR is ready to check for merging~~
Ready to merge! See https://github.com/QAComet/nextjs-starter-medusa/actions/runs/8430074236 for an example run that works and https://github.com/QAComet/nextjs-starter-medusa/actions/runs/8428959894 for an example run which fails and gives a playwright-report.zip file.

Github action for running tests on new PR's

---

src/lib/data/products.ts
src/modules/products/components/product-actions/index.tsx

**What**
- if variant has managed inventory check stocked quantity
---
FIXES CC-359

fix: check stocked quantity for managed variants

---

src/lib/data/products.ts

FIXES CC-564
CLOSES https://github.com/medusajs/medusa/issues/9432

fix: products pagination

---

package.json
src/modules/products/components/related-products/index.tsx
yarn.lock

**What**
- Fixes the query in RelatedProducts
- Updates dependencies, and removes client-types dependency.

fix: use tag_ids instead of tags

---

src/app/[countryCode]/(main)/order/[id]/transfer/[token]/page.tsx

**What**
- fix lint issue on build

fix: lint issue

---

src/app/[countryCode]/(checkout)/checkout/page.tsx
src/lib/data/payment.ts
src/modules/checkout/components/payment-wrapper/index.tsx
src/modules/checkout/components/payment-wrapper/stripe-wrapper.tsx
src/modules/checkout/components/payment/index.tsx
src/modules/checkout/templates/checkout-form/index.tsx

Few minor Stripe wrapper optimizations.

fix: stripe wrapper

---

src/lib/data/cart.ts
src/lib/data/fulfillment.ts
src/modules/checkout/components/shipping/index.tsx

**What**
- implement support for calculated shipping options in the checkout flow
---
CLOSES CMRC-788

feat: support calculated SO at checkout

---

src/modules/checkout/components/payment-container/index.tsx
src/modules/checkout/components/payment/index.tsx
src/modules/skeletons/components/skeleton-card-details/index.tsx

Fixes a bug where Stripe card payment sessions would not be initiated properly, resulting in the Card element not rendering. Also improved the credit card container UI.
- Fixed the logic for payment session initiation.
- Created a separate `<StripeCardContainer>` component that renders the Card element within the Radio button.
- Created a loading skeleton for the card details element.
https://github.com/user-attachments/assets/97023b07-e380-4d28-b0c5-dab0dfdf10e4

fix: stripe card details

---

src/modules/products/components/product-actions/mobile-actions.tsx

Fix the current option selected which doesn't update ui of slected variant.

fix current selected

---

src/modules/checkout/components/discount-code/index.tsx

**WHAT**: Handle invalid promo code gracefully
CLOSES: CORE-1117

fix(checkout): handle error on invalid promo code

---

src/lib/data/products.ts
src/modules/products/components/related-products/index.tsx

fix: typing for store product params
